sys:
  module: application  #模块
  name: web #应用
server:
  port: 11102
eureka:
  client:
    registry-fetch-interval-seconds: 3
  instance:
    lease-renewal-interval-in-seconds: 3 #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 5 #如果心跳检测一直没有发送，5秒后会从eureka服务器中将此服务剔除
spring:
  application:
    name: ${sys.module}
  profiles:
    active: local #环境配置- local：本地 dev：开发环境 qa：测试环境 uat：用户测试 pd：生产环境
  cloud:
    config:
      enable: false
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
logging:
  file: logs/${spring.application.name}.log

