application:
  product: saas #产品
  module: monitor #模块
  name: app #子模块名称
  code: 11399 #子模块ID
  displayName: 平台监控
  uploadFilePath:

server:
  port: 11399
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,text/css,application/javascript
    min-response-size: 256
eureka:
  client:
    registry-fetch-interval-seconds: 3
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      user:
        name: actuator
        password: 123456
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  application:
    name: ${application.product}-${application.module}-${application.name}
  profiles:
    active: local #环境配置- local：本地 dev：开发环境 qa：测试环境 uat：用户测试 pd：生产环境
  cloud:
    config:
      enable: false
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  mail:
    host: smtp.qq.com
    port: 587
    username: 2170290560@qq.com
    password: sekhkgopnoroebcj
    properties:
      mail:
        smtp:
          auth: true
#          starttls:
#            enable: true
#            required: true
  boot:
    admin:
      context-path: /admin
      discovery:
        converter:
          management-context-path: /actuator
  session:
    store-type: hash_map
management:
  security:
      enabled: true
  context-path: /actuator

security:
  user:
    name: actuator
    password: 123456
  basic:
    authorize-mode: authenticated
logging:
  file: logs/${spring.application.name}.log

