sys:
  module: maintenance  #模块
  name: web #应用

server:
  port: 11201
  compression:
    enabled: true
    mime-types: text/javascript,text/css,application/javascript,text/html,text/css,application/javascript,application/json
eureka:
  client:
    registry-fetch-interval-seconds: 3
    #register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: mysql
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  application:
    name: ${sys.module}
  profiles:
    active: local #环境配置- local：本地 dev：开发环境 qa：测试环境 uat：用户测试 pd：生产环境
  cloud:
    config:
      enable: false
logging:
  file: logs/${spring.application.name}.log

