eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://183.63.91.141:33060/aic_maintenance?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8&allowMultiQueries=true
    username: root
    password: daan_2017
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password: null
    database: 1
    timeout: 300
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 1

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

swagger:
  enabled: true
  base-package: net.aicoder.maintenance

hystrix:
  metrics:
    enabled: false
application:
  uploadFilePath: /usr/local/gonghr/apps/devp/dev/attachment