eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  redis:
    host: localhost
    port: 6379
    password: null
    database: 1
    timeout: 300
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 1